### ISSUE TITLE
python manage.py test doesn't work.

### ISSUE THREAD

**Issue by yxzuz** [gooddinosaur/ku-polls#52]
<img width="597" alt="Screenshot 2567-09-14 at 19 47 52" src="https://github.com/user-attachments/assets/60f7d4c3-daa0-47c3-849d-22ce562f7666">

But this command works just fine.
```
python manage.py test polls 
```

**Comment by gooddinosaur** [comment]
This occurred because I forgot to include the `__init__.py` in the polls directory. Now I added it already and `python manage.py test` working correctly.
![image](https://github.com/user-attachments/assets/9f5b2170-deab-437f-baf6-2f1f523f067a)
![image](https://github.com/user-attachments/assets/55da180f-eba6-4848-8a30-81560c71de4a)
